### ISSUE TITLE
Add section describing how exactly to do when editing a page/section

### ISSUE THREAD

**Issue by BioPsykOLD** [ipsych-community/wiki-genetics#6]
The bookdown format is really pretty and seems optimal to get an overview over the resources. It was not obvious at first where to look for the main document to make changes, but I guess it is this one, right?
https://github.com/ipsych-community/wiki-genetics/blob/master/index.Rmd

Maybe we can add that to the how to contribute section?

Is the long term plan to have only one file for everything or can we have more files later when content grows?

**Comment by privefl** [comment]
The plan is to get one different file for each different "page".

I wanted to do what you're asking for 2 hours ago but I got lazy :')

**Comment by BioPsykOLD** [comment]
ok, perhaps we should split this into two issues then: one for how to add content and the second for implementation of one topic per page. When I have done I will close this issue.

**Comment by privefl** [comment]
I am not sure I follow the difference.

**Comment by BioPsykOLD** [comment]
As they are two tasks they get one issue each, see #7 and #8
