### ISSUE TITLE
General - add the one-page-per-topic layout

### ISSUE THREAD

**Issue by BioPsykOLD** [ipsych-community/wiki-genetics#7]
To make it easier later when content grows and to avoid merge conflicts it can be good with one page per topic. As I understand @privefl has already planned for that.

**Comment by privefl** [comment]
I have added some section about "Contributing new pages" and some example file.

Is this what you were thinking of?

**Comment by BioPsykOLD** [comment]
It was exactly what I was thinking of, thanks!
